[versions]
gradle = '7.4.0-alpha10'
hilt = '2.43.2'
kotlin = '1.7.10'
room = "2.5.0-alpha03"
compose = "1.3.0-beta01"
composeCompiler = "1.3.0"
accompanist = "0.26.2-beta"
coroutines = "1.6.4"
ktor = "2.1.0"


[libraries]
build-agp = { module = "com.android.tools.build:gradle", version.ref = "gradle"}
build-kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
build-kover = "org.jetbrains.kotlinx:kover:0.6.0"
build-spotless = "com.diffplug.spotless:spotless-plugin-gradle:6.10.0"

room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }

compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
compose-text = { module = "androidx.compose.ui:ui-text-google-fonts", version.ref = "compose" }
compose-material = { module = "androidx.compose.material:material", version.ref = "compose" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
compose-runtime = { module = "androidx.compose.runtime:runtime-livedata", version.ref = "compose" }
m3 = { module = "androidx.compose.material3:material3", version = "1.0.0-beta01" }

compose-icons = { module = "androidx.compose.material:material-icons-extended", version.ref = "compose" }

core = { module = "androidx.core:core-ktx", version = "1.8.0" }
app-compat = { module = "androidx.appcompat:appcompat", version = "1.5.0" }
activity-compose = { module = "androidx.activity:activity-compose", version = "1.5.1" }

navigation = { module = "androidx.navigation:navigation-compose", version = "2.5.1" }

lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime-compose", version = "2.6.0-alpha01" }
lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version = "2.6.0-alpha01" }

accompanist-sysui = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "accompanist" }
accompanist-nav-animation = { module = "com.google.accompanist:accompanist-navigation-animation", version.ref = "accompanist" }
accompanist-pager = { module = "com.google.accompanist:accompanist-pager", version.ref = "accompanist" }
accompanist-pager-indicators = { module = "com.google.accompanist:accompanist-pager-indicators", version.ref = "accompanist" }
accompanist-swipe-refresh = { module = "com.google.accompanist:accompanist-swiperefresh", version.ref = "accompanist" }
accompanist-webview = { module = "com.google.accompanist:accompanist-webview", version.ref = "accompanist" }

coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
coroutines-play-services = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-play-services", version.ref = "coroutines" }

hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hilt" }
hilt-common = { module = "androidx.hilt:hilt-common", version = "1.0.0" }
hilt-nav = { module = "androidx.hilt:hilt-navigation-compose", version = "1.0.0" }
hilt-work = { module = "androidx.hilt:hilt-work", version = "1.0.0" }
hilt-android-compiler = { module = "androidx.hilt:hilt-compiler", version = "1.0.0" }

kotlinx-serialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version = "1.4.0" }

ktor-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-serialization = { module = "io.ktor:ktor-client-serialization", version.ref = "ktor" }
ktor-encoding = { module = "io.ktor:ktor-client-encoding", version.ref = "ktor" }
ktor-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }

okhttp-brotli = { module = "com.squareup.okhttp3:okhttp-brotli", version = "4.10.0" }
logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version = "4.10.0" }

landscapist-glide = { module = "com.github.skydoves:landscapist-glide", version = "1.6.1" }

kotlin-monad = { module = "com.michael-bull.kotlin-result:kotlin-result", version = "1.1.16" }

glance-widget = { module = "androidx.glance:glance-appwidget", version = "1.0.0-alpha03" }
splashscreen = { module = "androidx.core:core-splashscreen", version = "1.0.0" }
webkit = { module = "androidx.webkit:webkit", version = "1.5.0" }
browser = { module = "androidx.browser:browser", version = "1.4.0" }
profileinstaller = { module = "androidx.profileinstaller:profileinstaller", version = "1.2.0" }
work-manager = { module = "androidx.work:work-runtime-ktx", version = "2.7.1" }
jsoup = { module = "org.jsoup:jsoup", version = "1.15.3" }


junit = { module = "junit:junit", version = "4.13.2" }
truth = { module = "com.google.truth:truth", version = "1.1.3" }
truth-java8 = { module = "com.google.truth.extensions:truth-java8-extension", version = "1.1.3" }

mockk = { module = "io.mockk:mockk", version = "1.12.7" }
turbine = { module = "app.cash.turbine:turbine", version = "0.9.0" }

coroutine-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
ktor-mock = { module = "io.ktor:ktor-client-mock", version.ref = "ktor" }

robolectric = { module = "org.robolectric:robolectric", version = "4.8.2" }
arch-core-testing = { module = "androidx.arch.core:core-testing", version = "2.1.0" }
test-core-ktx = { module = "androidx.test:core-ktx", version = "1.4.0" }
junit-ktx = { module = "androidx.test.ext:junit-ktx", version = "1.1.3" }

android-junit = { module = "androidx.test.ext:junit", version = "1.1.3" }
espresso-core = { module = "androidx.test.espresso:espresso-core", version = "3.4.0" }
uiautomator = { module = "androidx.test.uiautomator:uiautomator", version = "2.2.0" }
benchmark-macro = { module = "androidx.benchmark:benchmark-macro-junit4", version = "1.2.0-alpha02" }


[bundles]
base = ["core", "app-compat", "activity-compose"]
compose = ["compose-ui", "compose-text", "compose-material", "compose-ui-tooling", "compose-runtime", "m3"]
lifecycle = ["lifecycle-runtime", "lifecycle-viewmodel"]
accompanist = ["accompanist-sysui", "accompanist-nav-animation", "accompanist-pager", "accompanist-swipe-refresh", "accompanist-pager-indicators", "accompanist-webview"]
coroutines = ["coroutines-core", "coroutines-android", "coroutines-play-services"]
room = ["room-ktx", "room-runtime"]
hilt = ["hilt-android", "hilt-common", "hilt-nav", "hilt-work"]
ktor = ["ktor-okhttp", "ktor-serialization", "ktor-encoding", "ktor-negotiation", "ktor-kotlinx-json", "logging-interceptor"]
testing = ["junit", "truth", "truth-java8", "mockk", "turbine", "coroutine-test", "ktor-mock", "robolectric", "arch-core-testing", "test-core-ktx", "junit-ktx"]
benchmark = ["android-junit", "espresso-core", "uiautomator", "benchmark-macro"]

[plugins]
hilt-plugin = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
android-application = { id = "com.android.application", version.ref = "gradle" }
android-library = { id = "com.android.library", version.ref = "gradle" }
spotless = { id = "com.diffplug.spotless", version = "6.10.0" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
hilt-android-plugin = { id = "com.google.dagger:hilt-android-gradle-plugin", version.ref = "hilt" }
google-services = { id = "com.google.gms:google-services", version = "4.3.13" }
perf-plugin = { id = "com.google.firebase:perf-plugin", version = "1.4.1" }
crashlytics-plugin = { id = "com.google.firebase:firebase-crashlytics-gradle", version = "2.9.1" }